vaadin/vaadin-checkbox

- .travis.yml
:tada:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/2)
> npm@5 is now npm@latest

- analysis.json
- vaadin-checkbox.html
Fixes #3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/4)
> Add @mixes Polymer.GestureEventListeners annotation

- test/vaadin-checkbox_test.html
- vaadin-checkbox.html
This PR fixes #8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/11)
> Fixes indeterminate state change on space press

- test/vaadin-checkbox_test.html
- vaadin-checkbox.html
This PR fixes #9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/10)
> Fixes 'aria-checked' attribute value states

- vaadin-checkbox.html
Fixes https://github.com/vaadin/vaadin-checkbox/issues/20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/22)
> Remove gray highlight when tapping disabled state

- vaadin-checkbox.html
Fixes #18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/21)
> Remove native outline for checkbox (Firefox)

- analysis.json
- vaadin-checkbox.html
The same as https://github.com/vaadin/vaadin-text-field/pull/108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/26)
> Remove Polymer.GestureEventListeners

- demo/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/30)
> Add explanation and link to indeterminate state docs

- test/vaadin-checkbox_test.html
- vaadin-checkbox.html
Fixes #24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/31)
> Add support for toggling by clicking the host and `.click()`

- vaadin-checkbox.html
Fixes #34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/36)
> Restore Gesture event listener

- test/vaadin-checkbox_test.html
- vaadin-checkbox.html
Connected to #42
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/43)
> Set checked to false on indeterminate changed

- analysis.json
- test/vaadin-checkbox_test.html
- vaadin-checkbox.html
Fixes #45 
Aligned implementation with vaadin-radio-button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/46)
> Fix name for iron-form use

- bower.json
- test/vaadin-checkbox_test.html
- vaadin-checkbox.html
Fixes #50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/51)
> Fix iron-form interoperability

- README.md
- bower.json
- src/vaadin-checkbox.html
Checks Polymer version and reports usage statistics in development mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/53)
> Use Vaadin.ElementMixin

- bower.json
- demo/index.html
- theme/valo/vaadin-checkbox.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/56)
> Update Valo dependency

- analysis.json
- src/vaadin-checkbox.html
- test/vaadin-checkbox_test.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/57)
> Remove ID from the label and native checkbox

- src/vaadin-checkbox.html
- test/vaadin-checkbox_test.html
Fixes #59
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/60)
> Set indeterminate to false when clicked the first time.

- theme/valo/vaadin-checkbox.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/61)
> Disable hover effect on touch devices

- test/vaadin-checkbox_test.html
Fixes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/65)
> Fix tests to work with iron-form 2.1.0

- demo/checkbox-a11y-demos.html
- demo/checkbox-basic-demos.html
- demo/checkbox-indeterminate-demos.html
Fixes #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/67)
> Convert indeterminate state demo to ES5

- src/vaadin-checkbox.html
Fixes #71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/72)
> Remove native outline from host

- theme/lumo/vaadin-checkbox.html
Fixes #58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/83)
> Remove will-change properties

- src/vaadin-checkbox.html
Exactly the same as https://github.com/vaadin/vaadin-radio-button/pull/60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/89)
> Remove margin on input[type="checkbox"]

- analysis.json
- src/vaadin-checkbox.html
- test/vaadin-checkbox_test.html
Fixes #81
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/92)
> Implement `change` event

- bower.json
- theme/material/vaadin-checkbox-styles.html
- theme/material/vaadin-checkbox.html
Connected to vaadin/vaadin-material-styles#49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/97)
> Adding theme/material

- analysis.json
- src/vaadin-checkbox.html
Connected to vaadin/components-team-tasks#403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/115)
> Remove Polymer mention in the API docs

- src/vaadin-checkbox-group.html
- test/.eslintrc
- test/vaadin-checkbox-group_test.html
Fixes #111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/116)
> Fix listeners on reattaching of the group

- demo/checkbox-indeterminate-demos.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/117)
> Remove Polymer legacy syntax from demo [skip ci]

- theme/material/vaadin-checkbox-group-styles.html
Fixes #120
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/121)
> Fix Material checkbox ripple cropped in Chrome [skip ci]

- src/vaadin-checkbox-group.html
- test/vaadin-checkbox-group_test.html
Fixes #123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/126)
> Fix checkbox-group not validating on focusout

- src/vaadin-checkbox.html
- test/accessibility.html
Fixes #25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/119)
> Set indeterminate false by default

- demo/checkbox-indeterminate-demos.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/135)
> Fix incorrect closing tag in demo [skip ci]

- src/vaadin-checkbox.html
- test/vaadin-checkbox_test.html
Fixes #136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/137)
> fix(checkbox): add missing styles for hidden attribute

- src/vaadin-checkbox.html
- test/vaadin-checkbox_test.html
Fixes #128 
Same as vaadin/vaadin-radio-button#79
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/139)
> fix(checkbox): set focusElement to input to avoid firefox issue

- src/vaadin-checkbox.html
- test/vaadin-checkbox-group_test.html
- test/vaadin-checkbox_test.html
Fixes #145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/146)
> fix: make change event not composed

- src/vaadin-checkbox.html
- test/accessibility.html
> Change value of aria-checked attribute to Boolean of checked property

- src/vaadin-checkbox-group.html
> docs: add JSDoc for attributes [skip ci] (#179)

- src/vaadin-checkbox-group.js
- src/vaadin-checkbox.d.ts
- src/vaadin-checkbox.js
> chore: align JSDoc, add change event [skip ci]

- src/vaadin-checkbox-group.html
- test/vaadin-checkbox-group_test.html
cherry pick of https://github.com/vaadin/web-components/pull/2232 for v14
cherry pick of https://github.com/vaadin/web-components/pull/2256 for v14
Fixes vaadin/flow-components#955
> fix: do not focus the field on helper element click

- src/vaadin-checkbox-group.html
- test/.eslintrc
- test/helpers.html
- test/validation.html
Backports the following PRs:
- https://github.com/vaadin/web-components/pull/4097
Part of https://github.com/vaadin/web-components/issues/5763
> feat: add methods to make setting invalid overridable (CP: 14)

- src/vaadin-checkbox.html
- test/vaadin-checkbox_test.html
Cherry-pick of #239 to `2.5` branch for Vaadin 14.10.
- Cherry-pick
> fix: call click on checkbox Space key up (#239) (CP: 2.5)
