vaadin/vaadin-checkbox

vaadin-checkbox.html
Fixes #5
Fixes checkbox not working on iPhone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/6)
=> Fixes checkbox not working on iPhone

bower.json
Connected to https://github.com/vaadin/vaadin-core/issues/127
Bump web-component-tester to 6.1.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/32)
=> Bump web-component-tester to 6.1.5

test/vaadin-checkbox_test.html, vaadin-checkbox.html
Connects to #42 
Fixes #48
Reverting to native checkbox behavior
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/47)
=> Revert "Set checked to false on indeterminate changed"

test/vaadin-checkbox_test.html
Now that PolymerElements/iron-form#239 is merged and released in `iron-form` 2.1.1 we can revert workaround used in tests. Also added native form, which was missed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/68)
=> Restore iron-form tests

src/vaadin-checkbox.html, test/vaadin-checkbox_test.html
Fixes #70 
Add `toggleChecked` to handle programmatically invoked click
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/78)
=> Add toggleChecked to handle programmatically invoked click

.travis.yml, test/accessibility.html, test/vaadin-checkbox_test.html, wct.conf.js
Connected to vaadin/components-team-tasks#332
Also did some cleanup to eliminate the single legacy `Polymer.dom` usage.
The `mock-interactions` change is needed because of the fact that `mock-interactions.js` still use the `Polymer.Base.async` and the HTML file imports the needed dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/82)
=> Use bare module specifiers in the P3 conversion

.gitignore, package.json, test/vaadin-checkbox_test.html, wct.conf.js
The same as https://github.com/vaadin/vaadin-element-skeleton/pull/127
1 test was missing to 100% coverage, so I added it in score of this PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/94)
=> Add test coverage threshold

analysis.json, bower.json, demo/checkbox-group-demos.html, demo/demos.json, demo/index.html, src/vaadin-checkbox-group.html, test/test-suites.js, test/vaadin-checkbox-group_test.html, theme/lumo/vaadin-checkbox-group-styles.html, theme/lumo/vaadin-checkbox-group.html, theme/material/vaadin-checkbox-group-styles.html, theme/material/vaadin-checkbox-group.html, vaadin-checkbox-group.html, wct.conf.js
Fixes #100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/103)
=> Added vaadin-checkbox-group MVP

bower.json, src/vaadin-checkbox-group.html, test/vaadin-checkbox-group_test.html
Fixes #109 
Note that we need 2 observers now:
- one for "splices" - to cover value change from outside, using array mutation methods (see new tests)
- second one for value change from the inside, as the multi-property observer is no longer reliable in the matter of "initial state" check for validation (old value can be only available in single-property observer, so the `undefined` check is what matters)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/110)
=> Set value to the new array instance every time

src/vaadin-checkbox.html, test/vaadin-checkbox_test.html
Fixes #130 
Consider the label empty also if there is only one empty text node inside the `<vaadin-checkbox>` tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/129)
=> Fix empty slot check

src/vaadin-checkbox-group.html, test/vaadin-checkbox-group_test.html
`checkboxgroup` doesn't seem to be a real role. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques#Widget_roles
Also fails to Lighthouse A11Y tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/131)
=> Remove checkboxgroup role

src/vaadin-checkbox-group.html, test/vaadin-checkbox-group_test.html, wct.conf.js
Two fixes in separate commits (so don't squash).
These are mostly relevant for the Flow component, as Flow always creates the child checkboxes dynamically.
vaadin/vaadin-checkbox-flow#83
vaadin/vaadin-checkbox-flow#89
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/147)
=> Fix checkbox-group issues with dynamically added checkboxes

bower.json
There is already a commit merged to `master` that depends on `DirMixin`.
We should bump version and make it explicit that it needs a new minor.
=> feat: bump element-mixin to 2.3.0

src/vaadin-checkbox-group.html, test/vaadin-checkbox-group_test.html
Fixes #161. This is a PR for `2.2` branch, has to be cherry-picked to master later on.
=> fix: prevent incorrect console warning

bower.json, theme/lumo/vaadin-checkbox-styles.html
Prevent the checkbox from turning into a full circle, which could easily happen when there’s only one border-radius property to control.
Connected to vaadin/vaadin-lumo-styles#63
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-checkbox/140)
=> Use --lumo-border-radius-s

src/vaadin-checkbox.html, test/accessibility.html
Cherry-pick of #164 to `2.2` branch.
=> fix: set aria-checked properly when checked is null [2.2] (#164)

bower.json, gen-tsd.json, magi-p3-post.js, package.json, src/vaadin-checkbox-group.html, src/vaadin-checkbox.html
Fixes #171 
Generated TS definitions look like this:
```ts
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {GestureEventListeners} from '@polymer/polymer/lib/mixins/gesture-event-listeners.js';
import {ThemableMixin} from '@vaadin/vaadin-themable-mixin/vaadin-themable-mixin.js';
import {ControlStateMixin} from '@vaadin/vaadin-control-state-mixin/vaadin-control-state-mixin.js';
import {ElementMixin} from '@vaadin/vaadin-element-mixin/vaadin-element-mixin.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';
declare class CheckboxElement extends
ElementMixin(
ControlStateMixin(
ThemableMixin(
GestureEventListeners(
PolymerElement)))) {
readonly focusElement: HTMLInputElement;
name: string;
checked: boolean;
indeterminate: boolean;
value: …
```
=> feat: prepare for TS defs generation [skip ci]

src/vaadin-checkbox-group.html
Connected to vaadin/vaadin-core#257
Note, this is a PR for `2.4` branch. When cherry-picking it to master, we need to also include `helperText` property.
=> docs: add JSDoc for attributes [skip ci]

src/vaadin-checkbox-group.d.ts, src/vaadin-checkbox-group.js
Let's remove this from JSDoc as we do it for other components as well.
=> docs: remove mentions of iron-form [skip ci]

src/vaadin-checkbox-group.d.ts, src/vaadin-checkbox.d.ts
Looks like the event type can not be inferred when using event name autocomplete provided by VSCode plugin. 
So I changed to use `@fires {CustomEvent}` without a type. Also, added the events descriptions.
=> chore: update JSDoc for custom events [skip ci]

test/a11y.test.js, test/checkbox.test.js
- After d7692ae144017af71b4629a7733a6fe219faf648 some tests became duplicate as they were testing the same thing. 
- One of the `role` tests was incorrect, updated to test the `presentation` role.
=> test: cleanup duplicate unit tests

src/vaadin-checkbox-group.js, web-test-runner.config.js
The usage of polyfilled `_activeElement` is no longer needed and can be removed.
=> refactor: remove Safari 9 workaround

src/vaadin-checkbox.html, test/vaadin-checkbox_test.html
Part of https://github.com/vaadin/web-components/issues/6737
This change adds manual `click()` call on `keyup` event for better backwards compatibility.
Alternatively, we could just remove `event.preventDefault()` from `keydown` and `keyup` listeners. 
This enables native `click` event to be fired on <kbd>Space</kbd> key press, at least in modern browsers.
- Bugfix
=> fix: call click on checkbox Space key up
